### ISSUE TITLE
create page of tutorials with link

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/webpages#8]
We need to put up a list of videos somewhere. 
I propose we add a new page and nav link on the
web site for tutorials.  It'd start with:

* Ehsan Karim's video:  https://www.youtube.com/watch?v=tLprFqSWS1w
* Shravan Vashishth's tutorial for psychologists
* my MLSS lectures (not available online yet)
* Andrew's appendix to BDA, available free online
* link to Kruschke's book (there's a chapter)

**Comment by betanalpha** [comment]
I was deathly sick, but https://www.youtube.com/watch?v=pHsuIaPbNbY

**Comment by bob-carpenter** [comment]
done, validated, and uploaded.  Also removed unused nav and out-of-date template from both the current master branch and from the server.
